version: "3.1"

services:
  postgres:
    container_name: postgres-db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./prisma/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=my_local
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=passw0rd
